package com.redes.app.network

object MobileEndpoints {
    const val ME = "/api/mobile/me"
    const val BOOTSTRAP = "/api/mobile/bootstrap"
    const val PRESENCE = "/api/mobile/presencia"
    const val TECNICO_HOME = "/api/mobile/tecnico/home"
    const val TECNICO_ORDERS = "/api/mobile/tecnico/ordenes"
    const val TECNICO_STOCK = "/api/mobile/tecnico/stock"
    const val TECNICO_MAP = "/api/mobile/tecnico/mapa"

    const val TRACKING = "/api/mobile/tracking"
    const val TECNICO_CUADRILLAS_MAPA = "/api/mobile/tecnico/cuadrillas-mapa"
    const val ALERTAS_APP = "/api/mobile/alertas-app"
    const val INICIO_JORNADA = "/api/mobile/inicio-jornada"

    const val COORDINADOR_INICIO = "/api/mobile/coordinador/inicio"
    const val COORDINADOR_CUADRILLAS = "/api/mobile/coordinador/cuadrillas"
    const val COORDINADOR_MAPA = "/api/mobile/coordinador/mapa"
    const val COORDINADOR_CUADRILLAS_MAPA = "/api/mobile/tecnico/cuadrillas-mapa"
    const val COORDINADOR_STOCK = "/api/mobile/coordinador/stock"
    const val COORDINADOR_AUDITORIA = "/api/mobile/coordinador/auditoria"
    const val COORDINADOR_PREDESPACHO = "/api/mobile/coordinador/predespacho"
    const val COORDINADOR_VENTAS = "/api/mobile/coordinador/ventas"
    const val COORDINADOR_PLANTILLAS = "/api/mobile/coordinador/plantillas"
    const val COORDINADOR_AUDITORIA_SUSTENTAR = "/api/mobile/coordinador/auditoria/sustentar"
    const val COORDINADOR_LIQUIDACION = "/api/mobile/coordinador/liquidacion"
    const val COORDINADOR_LIQUIDACION_PRELIQUIDACION = "/api/mobile/coordinador/liquidacion/preliquidacion"
    const val COORDINADOR_LIQUIDACION_LIQUIDAR = "/api/mobile/coordinador/liquidacion/liquidar"

    const val SUPERVISOR_HOME = "/api/mobile/supervisor/home"
    const val SUPERVISOR_ORDERS = "/api/mobile/supervisor/ordenes"
    const val SUPERVISOR_MAPA = "/api/mobile/supervisor/mapa"
    const val SUPERVISOR_CUADRILLAS_MAPA = "/api/mobile/supervisor/cuadrillas-mapa"
    const val SUPERVISOR_SUPERVISION = "/api/mobile/supervisor/supervision"
    const val SUPERVISOR_JORNADA = "/api/mobile/supervisor/jornada"
    const val SUPERVISOR_GARANTIAS_UPDATE = "/api/mobile/supervisor/garantias/update"

    const val ALMACEN_STOCK = "/api/mobile/almacen/stock"
    const val ALMACEN_LIQUIDACION = "/api/mobile/almacen/liquidacion"
    const val ALMACEN_LIQUIDACION_PRELIQUIDACION = "/api/mobile/almacen/liquidacion/preliquidacion"
    const val ALMACEN_LIQUIDACION_SN_LOOKUP = "/api/mobile/almacen/liquidacion/sn-lookup"
    const val ALMACEN_LIQUIDACION_LIQUIDAR = "/api/mobile/almacen/liquidacion/liquidar"
    const val ALMACEN_INSTALACIONES = "/api/mobile/almacen/instalaciones"
    const val ALMACEN_CUADRILLAS_MAPA = "/api/mobile/tecnico/cuadrillas-mapa"

    fun comunicadoSeen(id: String): String = "/api/mobile/comunicados/$id/seen"
    fun tecnicoOrderDetail(id: String): String = "/api/mobile/tecnico/ordenes/$id"
    fun supervisorOrderDetail(id: String): String = "/api/mobile/supervisor/ordenes/$id"
    fun coordinadorOrdenDetail(id: String): String = "/api/mobile/coordinador/ordenes/$id"
}
